### POST poprawny (201)
POST http://localhost:8080/webapi/theatres
Content-Type: application/json
Accept-Language: pl

{
  "name": "Teatr Nowy",
  "logo": "https://example.com/nowy.png"
}

### POST błędny – za krótka nazwa (400 po polsku)
POST http://localhost:8080/webapi/theatres
Content-Type: application/json
Accept-Language: pl

{
  "name": "X",
  "logo": "https://example.com/nowy.png"
}

### POST błędny – po włosku
POST http://localhost:8080/webapi/theatres
Content-Type: application/json
Accept-Language: it

{
  "name": "X",
  "logo": "https://example.com/nowy.png"
}

### POST błędny – brak name (null, po angielsku)
POST http://localhost:8080/webapi/theatres
Content-Type: application/json
Accept-Language: en

{
  "logo": "https://example.com/nowy.png"
}
